# -*- coding: utf-8 -*-
"""Crypto Sentiment Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qvNNUQ6zaOQLcK7-KK4U8IGk9AReWsoa
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

sentiment = pd.read_csv("/content/fear_greed_index (1).csv")
trades = pd.read_csv("/content/historical_data (1).csv")

sentiment['date'] = pd.to_datetime(sentiment['date'])

trades['Timestamp IST'] = pd.to_datetime(trades['Timestamp IST'], format="%d-%m-%Y %H:%M", errors='coerce')

trades['Date'] = trades['Timestamp IST'].dt.date
sentiment['Date'] = sentiment['date'].dt.date

print(f"Trades Date Range: {trades['Date'].min()} to {trades['Date'].max()}")
print(f"Trades NaT count: {trades['Date'].isnull().sum()}")
print(f"Sentiment Date Range: {sentiment['Date'].min()} to {sentiment['Date'].max()}")
print(f"Sentiment NaT count: {sentiment['Date'].isnull().sum()}")

merged = pd.merge(trades.astype({'Date': 'datetime64[ns]'}), sentiment.astype({'Date': 'datetime64[ns]'}), on='Date', how='inner')

merged['Closed PnL'] = pd.to_numeric(merged['Closed PnL'], errors='coerce')
merged.groupby('classification')['Closed PnL'].mean()

merged['classification'].value_counts()

merged.groupby('classification')['Closed PnL'].mean()

print(merged.columns)

merged.groupby(['classification', 'Side'])['Closed PnL'].mean()

sns.boxplot(x='classification', y='Closed PnL', data=merged)

plt.show()

sns.barplot(x='classification', y='Closed PnL', data=merged)

merged['win'] = merged['Closed PnL'] > 0

merged.groupby('classification')['win'].mean()

merged.groupby('classification')['Closed PnL'].std()

winrate = merged.groupby('classification')['win'].mean()
print(winrate)

sentiment_pnl = merged.groupby('classification')['Closed PnL'].mean()
print(sentiment_pnl)

import os

plt.figure(figsize=(10,5))
sns.boxplot(x='classification', y='Closed PnL', data=merged)
plt.title("PnL Distribution by Sentiment")
plt.tight_layout()

output_dir = 'outputs'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

plt.savefig(os.path.join(output_dir, "pnl_distribution.png"))

from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

encoder = LabelEncoder()

merged['side_encoded'] = encoder.fit_transform(merged['Side'])
merged['sentiment_encoded'] = encoder.fit_transform(merged['classification'])

merged['hour'] = merged['Timestamp IST'].dt.hour

features = [
    'Size Tokens',
    'hour',
    'side_encoded',
    'sentiment_encoded'
]

X = merged[features]
y = merged['win']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

print("\nMODEL PERFORMANCE")
print(classification_report(y_test, predictions))

importance = pd.DataFrame({
    'Feature': features,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(by='Importance', ascending=False)

print("\nFeature Importance")
print(importance)

plt.figure(figsize=(8,5))
sns.barplot(x='Importance', y='Feature', data=importance)
plt.title("Feature Importance")
plt.tight_layout()
plt.savefig("outputs/feature_importance.png")

cluster_data = merged[['Size Tokens', 'Closed PnL']].dropna()

kmeans = KMeans(n_clusters=3, random_state=42)

cluster_data['cluster'] = kmeans.fit_predict(cluster_data)

plt.figure(figsize=(8,5))
sns.scatterplot(
    x='Size Tokens',
    y='Closed PnL',
    hue='cluster',
    data=cluster_data
)

plt.title("Trader Clusters")
plt.tight_layout()
plt.savefig("outputs/trader_clusters.png")

print("\nAnalysis Completed Successfully")

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, predictions)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted False', 'Predicted True'],
            yticklabels=['Actual False', 'Actual True'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

"""### Training and Evaluating Logistic Regression"""

from sklearn.linear_model import LogisticRegression

log_reg_model = LogisticRegression(random_state=42, solver='liblinear')

log_reg_model.fit(X_train, y_train)
log_reg_predictions = log_reg_model.predict(X_test)

print("\nLOGISTIC REGRESSION MODEL PERFORMANCE")
print(classification_report(y_test, log_reg_predictions))

"""### Confusion Matrix for Logistic Regression"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm_log_reg = confusion_matrix(y_test, log_reg_predictions)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_log_reg, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted False', 'Predicted True'],
            yticklabels=['Actual False', 'Actual True'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix for Logistic Regression')
plt.show()

from sklearn.metrics import roc_curve, roc_auc_score
import os


rf_probs = model.predict_proba(X_test)[:, 1]
log_reg_probs = log_reg_model.predict_proba(X_test)[:, 1]

rf_fpr, rf_tpr, _ = roc_curve(y_test, rf_probs)
rf_auc = roc_auc_score(y_test, rf_probs)

log_reg_fpr, log_reg_tpr, _ = roc_curve(y_test, log_reg_probs)
log_reg_auc = roc_auc_score(y_test, log_reg_probs)


plt.figure(figsize=(10, 7))
sns.lineplot(x=rf_fpr, y=rf_tpr, label=f'Random Forest (AUC = {rf_auc:.2f})')
sns.lineplot(x=log_reg_fpr, y=log_reg_tpr, label=f'Logistic Regression (AUC = {log_reg_auc:.2f})')


plt.plot([0, 1], [0, 1], 'k--', label='Random Guess (AUC = 0.50)')

plt.xlabel('False Positive Rate (FPR)')
plt.ylabel('True Positive Rate (TPR)')
plt.title('ROC Curve Comparison: Random Forest vs. Logistic Regression')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()


if not os.path.exists('outputs'):
    os.makedirs('outputs')
plt.savefig(os.path.join('outputs', 'roc_curve_comparison.png'))

plt.show()

!npm install localtunnel

!streamlit run app.py &>/content/logs.txt &

!npx localtunnel --port 8501

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# 
# st.title("Crypto Dashboard")
# 
# st.write("Streamlit running successfully!")